package eusocialcooperation.scheduler.dispatcher

import java.util.concurrent.atomic.AtomicReference
import eusocialcooperation.scheduler.datapoint.DataPoint
import org.apache.pekko.actor.typed.Behavior
import com.typesafe.config.Config
import eusocialcooperation.scheduler._
import Dispatcher.Command
import Dispatcher.WorkerFactory
import eusocialcooperation.scheduler.datapoint.DataPointActor
import eusocialcooperation.scheduler.datapoint.PekkoDataPoint
import org.apache.pekko.actor.typed.scaladsl.Behaviors
import Dispatcher.AddProspect
import org.apache.pekko.actor.typed.ActorRef
import org.apache.pekko.actor.typed.scaladsl.ActorContext
import scala.concurrent.duration.DurationLong

object PekkoDispatcher extends Dispatcher {
  def apply(
    pointsMemory: AtomicReference[Set[DataPoint[Sample]]],
    prospectsMemory: AtomicReference[Set[DataPoint[Point]]]
  )(implicit
      appConfig: Config,
      mdc: Map[String, String]
  ): Behavior[Dispatcher.Command] =
    apply(
      pointsMemory
      , prospectsMemory
      , (duration, ctx, i, sampleUnit, prospectUnit) => ctx.spawn(Worker(kernel, ctx.self, duration)(using sampleUnit = sampleUnit, prospectUnit = prospectUnit), s"worker-$i")
    )

  def apply(
    pointsMemory: AtomicReference[Set[DataPoint[Sample]]]
    , prospectsMemory: AtomicReference[Set[DataPoint[Point]]]
    ,  workerFactory: WorkerFactory
  )(implicit
      appConfig: Config,
      mdc: Map[String, String]
  ): Behavior[Command] = super.apply(workerFactory) { (ctx, run, experimentName, parentBehavior) =>
    Behaviors.withMdc(mdc) {
      val sampleActor =
        ctx.spawn(DataPointActor[Sample](pointsMemory), "sampleActor")
      val pointActor = ctx.spawn(
        DataPointActor[Point](prospectsMemory),
        "pointActor"
      )

      val sampleUnit = PekkoDataPoint
            .getActorDataPointUnit[Sample](sampleActor, ctx.system.scheduler)
      val prospectUnit = PekkoDataPoint
            .getActorDataPointUnit[Point](pointActor, ctx.system.scheduler)
      Behaviors.receiveMessage(
        active(
          Set.empty,
          sampleUnit,
          prospectUnit,
          parentBehavior(sampleUnit, prospectUnit),
          ctx
        )
      )
    }
  }
  /**
    * 
    * 
    *
    * @param pointsMemory
    *   A reference to the collection of points generated by the system. It is
    *   expected that this is provided empty, and the client retains a reference
    *   to this container to inspect the points after the algorithm completes.
    * @param prospectsMemory
    *   A reference to the collection of prospects generated by the system. It
    *   is expected that this is provided empty, and the client retains a
    *   reference to this container to inspect the prospects after the algorithm
    *   completes.
    * @param pointUnit
    * @param parentBehavior
    * @param ctx
    * @return
    */
  protected def active(
      prospects: Set[DataPointP],
      sampleUnit: DataPoint.DataPointUnit[Sample],
      pointUnit: DataPoint.DataPointUnit[Point],
      parentBehavior: PartialFunction[Dispatcher.Command, Behavior[
        Dispatcher.Command
      ]],
      ctx: ActorContext[Dispatcher.Command]
  ): PartialFunction[Dispatcher.Command, Behavior[Dispatcher.Command]] = {
    val t: PartialFunction[Dispatcher.Command, Behavior[Dispatcher.Command]] = {
      case Dispatcher.AddProspect(point, delayMs) =>
        ctx.log.info(s"Adding prospect: $point with delay: $delayMs ms")
        ctx.scheduleOnce(
          delayMs.milliseconds,
          ctx.self,
          Dispatcher.RemoveProspect(point)
        )
        Behaviors.receiveMessage(
          active(
            prospects + point,
            sampleUnit,
            pointUnit,
            parentBehavior,
            ctx
          )
        )
      case Dispatcher.RemoveProspect(point) =>
        ctx.log.info(s"Removing prospect: $point")
        Behaviors.receiveMessage(
          active(
            prospects - point,
            sampleUnit,
            pointUnit,
            parentBehavior,
            ctx
          )
        )
      case Dispatcher.RequestPoints(replyTo) =>
        replyTo ! Dispatcher.RequestedPoints(prospects)
        Behaviors.receiveMessage(
          active(
            prospects,
            sampleUnit,
            pointUnit,
            parentBehavior,
            ctx
          )
        )
    }
    t `orElse` parentBehavior
  }

}
