eusocialcooperation.scheduler {
    durationMs = 300000
    dispatcher {
        numWorkers = 30
    }
    workers {
        loopDelayMs = 50
        explorer {
            numPointsToExplore = 10
            threshold = 0.05
            explorationRadius = 0.01
            delayPerProspectMs = 10
        }
        exploiter {
            increment = 0.001
            fuzziness = 0.01
        }
    }
}
