eusocialcooperation.scheduler {
    // Duration the experiment with run. Required
    //duration = 300000
    dispatcher {
        // The number of workers the dispatcher will use to run the experiment. Required
        //numWorkers = 30
    }
    workers {
        // An artificial delay introduced into the main loop of the workers. Optional, defaults to 50 ms.
        //loopDelay = 50 ms
        distribution {
            // The type of distribution to use when randomly selecting a prospect for an exploiter. Required.
            //type = "uniform"
        }
        explorer {
            // The maximum number of points the explorer will explore before checking if it should change to an exploiter, or continue exploring. Required.
            //numPointsToExplore = 10
            // The value below which the explorer will consider the point a prospect for further, more detailed exploration for an exploiter. Required.
            //threshold = 0.05
            // The length of a step the explorer will take between testing the space. Required.
            //explorationRadius = 0.01
            // The amount of time a prospect should remain visible to workers before it is removed. Required.
            //delayPerProspect = 10 ms
        }
        exploiter {
            // The distance between the points the exploiter will test in the 11x11 grid around the prospect. Required.
            //increment = 0.001
            // The upper-bound of the random offset introduced by an exploiter to avoid complete duplication when a prospect is chosen by multiple exploiters. Required.
            //fuzziness = 0.01
        }
    }
}
