eusocialcooperation.scheduler {
     workers {
        loopDelay = 50
        weightPerProspect = 0.2
        distribution = {
            type = "uniform"
        }
     }
}

# TODO: This should probably be double-checked that it was actually used. There were a lot of changes made at the same time.
pekko.coordinated-shutdown.phases {
  eusocialcooperation-stop-workers {
    depends-on = ["before-service-unbind"]
    timeout = 10s
  }

  service-unbind {
    depends-on = ["before-service-unbind", "eusocialcooperation-stop-workers"]
  }
}