# This file is for the non-experiment configuration information, such as the pekko configuration.

pekko {
    coordinated-shutdown.exit-jvm = on
    cluster {
      shutdown-after-unsuccessful-join-seed-nodes = 60s
      downing-provider-class = org.apache.pekko.cluster.sbr.SplitBrainResolverProvider
    }
    extensions = ["org.apache.pekko.management.cluster.bootstrap.ClusterBootstrap"]
    actor {
      provider = cluster
        serialization-bindings {
          "eusocialcooperation.scheduler.datapoint.DataPoint" = jackson-cbor
        }
    }
    management.cluster.bootstrap.contact-point-discovery {
        service-name = hive # Not sure what this does, now, since it's not the same as pod-label-selector
        discovery-method = kubernetes-api
    }
    discovery {
      kubernetes-api {
        pod-namespace = "hive"
      }
    }
}

eusocialcooperation.scheduler {
  postgres_db {
    profile = "slick.jdbc.PostgresProfile$"
    db {
      connectionPool = "HikariCP"
      dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
      properties = {
          portNumber = "5432"
      }
      numThreads = 2 # Currently set to 2 because I'm using vCPU values of 2. Not sure if that's the right parameter in a clustered environment.
    }
  }
}