# This file is for the non-experiment configuration information, such as the pekko configuration.

pekko {
    coordinated-shutdown.exit-jvm = on
    cluster {
      shutdown-after-unsuccessful-join-seed-nodes = 60s
      # min-nr-of-members = 2 # Needs to be provided by the commandline? Or automatic with Kubernetes?
      downing-provider-class = org.apache.pekko.cluster.sbr.SplitBrainResolverProvider
    }
    extensions = ["org.apache.pekko.management.cluster.bootstrap.ClusterBootstrap"]
    actor {
      provider = cluster
        serialization-bindings {
          "eusocialcooperation.scheduler.datapoint.DataPoint" = jackson-cbor
        }
    }
    management.cluster.bootstrap.contact-point-discovery {
        service-name = hive # Not sure what this does, now, since it's not the same as pod-label-selector
        discovery-method = kubernetes-api
    }
    discovery {
      kubernetes-api {
        #pod-namespace-path = "/var/run/secrets/kubernetes.io/serviceaccount/namespace"
        pod-namespace = "hive"
      }
    }
}

eusocialcooperation.scheduler {
  postgres_db {
    profile = "slick.jdbc.PostgresProfile$"
    db {
      connectionPool = "HikariCP"
      dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
      properties = {
          portNumber = "5432"
      }
      numThreads = 10
      # TODO: Probably should set this to something. It defaults to 5 * numThreads, which is 50, but right now it makes approximately 30 connections per node
    }
  }
}