package eusocialcooperation.scheduler

//import org.jzy3d.chart.Chart
//import org.jzy3d.chart.factories.IChartFactory
//import org.jzy3d.plot3d.primitives.Scatter
//import org.jzy3d.maths.Coord3d
//import org.jzy3d.maths.Coord2d
//import org.jzy3d.plot2d.primitives.ScatterSerie2d
//import org.jzy3d.maths.Coord2d
//import org.jzy3d.plot2d.primitives.ScatterPointSerie2d
import scala.collection.JavaConverters._
//import org.jzy3d.colors.colormaps.ColorMapGrayscale
//import org.jzy3d.colors.Color
import scalafx.scene.Node
import org.jfree.chart3d.Chart3D
import org.jfree.chart.JFreeChart

/** A class that generates charts.
  *
  * The idea here was that I wanted to isolate the code that made decisions like
  * how the legends were formatted and how to process the datasets from the code
  * controlling the UI, because I knew I wanted to switch to JavaFX. However, in
  * the process of moving to JavaFX, I also switched to JFree Chart, and there
  * was some consideration of using implementations of this trait to make the
  * system flexible with which charting technology to use. Not for being dynamic
  * at runtime, but just to make switching implementations easier. But I hit a
  * wall where I couldn't get jzy3d quite like I wanted, and the system couldn't
  * be flexible in both the UI framework and the chart implementation, to
  * there's not much point. The Jzy3d implementation is just commented out, but
  * kept in case it is useful later, and the interface is just overhead to
  * making changes to
  * {@see eusocialcoordination.scheduler.charter.JFreeCharter}. But keeping the
  * "charter" separate from the UI controller has proven useful in that it
  * enabled an easy transition to a headless mode.
  */
trait Charter {

  /** Generates the 3D chart showing the points generated by the exploiters.
    *
    * @param pointsData
    *   All 3D points generated. The charter is expecting to filter by the phase
    *   in which the points were generated.
    * @param prospects
    *   All of the prospects generated.
    * @return
    *   A 3D chart showing the points generated by the exploiters, with the
    *   prospects added with an assumed height of 0.
    */
  def getMainChart(
      pointsData: Set[DataPoint[Sample]],
      prospects: Set[DataPoint[Point]]
  ): Chart3D
  /**
    * Generates a 2D chart showing the points generated by the exploiters (with their heights removed) and all prospects, in order to show which prospects were explored and how extensively.
    *
    * @param pointsData
    *   All 3D points generated. The charter is expecting to filter by the phase
    *   in which the points were generated, and to remove the height of the points to show them in 2D.
    * @param prospects
    *   All of the prospects generated.
    * @return
    *   A 2D chart showing the points generated by the exploiters (with their heights removed) and all prospects.
    */
  def getPoints2DChart(
      pointsData: Set[DataPoint[Sample]],
      prospects: Set[DataPoint[Point]]
  ): JFreeChart
  /**
    * Generates a 2D chart showing the number of exploiter points generated around each prospect and the variance of those points, in order to show how extensively each prospect was explored and how promising it was.
    *
    * @param pointsData
    *   All 3D points generated. The charter is expecting to filter by the phase
    *   in which the points were generated, and to group the points by their parent prospect.
    * @return
    *   A 2D chart showing the number of exploiter points generated around each prospect and the variance of those points.  
    */
  def getClusterChart(pointsData: Set[DataPoint[Sample]]): JFreeChart
  /**
    * Generates a 2D chart showing the number of prospects in the queue at regular intervals.
    * 
    * I'm not sure if this is useful. The behavior of the exploiter can't effect the queue, but the queue length effects the behavior of the exploiters. It may be useful as an indicator of the number of explorers.
    *
    * @param lengthSamples
    *  A list of samples of the length of the queue at regular intervals. Each sample is a tuple of the time the sample was taken and the length of the queue at that time.
    * @return
    *   A 2D chart showing the number of prospects in the queue at regular intervals.
    */
  def getLengthSamplesChart(lengthSamples: List[(Long, Int)]): JFreeChart
}
/*
class Jzy3dCharter extends LoggingComponent with Charter {
  def getMainChart(pointsData: Set[DataPoint[Sample]], prospects: Set[DataPoint[Point]], factory: IChartFactory): Chart = {
    val exploiterPoints = pointsData.filter(_.phase == DataPoint.Phase.Exploiter)
    logger.info("Exploiter points count: {}", exploiterPoints.size)
    val scatter = new Scatter(exploiterPoints.map(p => new org.jzy3d.maths.Coord3d(p.value._1.toDouble, p.value._2.toDouble, p.value._3.toDouble)).toArray)
    scatter.setColor(new org.jzy3d.colors.Color(0, 0, 0))
    scatter.setWidth(5.0f)

    val prospectsData = prospects.map(p => new Coord3d(p.value._1.toDouble, p.value._2.toDouble, 0)).toArray
    logger.info("Prospects count: {}", prospectsData.length)
    val prospectsScatter = new Scatter(prospectsData)
    prospectsScatter.setColor(new org.jzy3d.colors.Color(0, 255, 0))
    prospectsScatter.setWidth(5.0f)
    //val quality = Quality.Advanced

    /*
    val explorerPoints = pointsData.filter(_.phase == DataPoint.Phase.Explorer).groupBy(_.actorName)
    for ((actorName, pts) <- explorerPoints) {
        //println(s"Actor $actorName has ${pts.size} explorer points.")
        new LineStrip()
        val lineStrip = new LineStrip(pts.toSeq.sortBy(_.sequenceNumber).map(p => new org.jzy3d.maths.Coord3d(p.value._1.toDouble, p.value._2.toDouble, p.value._3.toDouble)).toSeq.asJava)
        lineStrip.setShowSymbols(true)
        //lineStrip.setWidth(5.0f)
        lineStrip.setColor(new org.jzy3d.colors.Color((Random.nextFloat() * 0.5f) + 0.5f, (Random.nextFloat() * 0.5f) + 0.5f, (Random.nextFloat() * 0.5f) + 0.5f))
        chart.add(lineStrip)
    }
 */
    
    val mainChart = factory.newChart()
    mainChart.add(scatter)
    mainChart.add(prospectsScatter)
    mainChart.open("Data Points", 800, 600)
    mainChart
  }

  def getClusterChart(pointsData: Set[DataPoint[Sample]], factory: IChartFactory): Chart = {
    val clusterThingMap = pointsData
        .filter(p => p.parent.isDefined && (p.phase == DataPoint.Phase.Exploiter))
        .groupBy(_.parent.get)
        .map((t) => {
            val (p, pts) = t
            val average = pts.foldLeft(BigDecimal(0.0))((acc, p) => acc + p.value._3) / pts.size
            (p -> (pts, average))
        })
        .map((t) => {
            val (p, (pts, average)) = t
            (p -> (pts.size, (pts.foldLeft(BigDecimal(0.0))((acc, p) => {
                acc + (p.value._3 - average).pow(2)
            }) / pts.size)))
        })
        .map((t) => {
            val (p, (count, variance)) = t
            (p -> new Coord2d(count.toDouble, variance.toDouble))
        })
    
    clusterThingMap.foreach((t) => {
        val (p, coord) = t
        logger.info(s"Parent point (${p.asInstanceOf[DataPoint[Point]].value._1}, ${p.asInstanceOf[DataPoint[Point]].value._2}) has ${coord.x} exploiter children and variance ${coord.y}.")
    })
    val clusterThingData = clusterThingMap.values.toArray
    println(s"Length ${clusterThingData.length}")
    //val clusterThingScatter = new ScatterPointSerie2d("Cluster Data")
    val clusterThingScatter = new Scatter(clusterThingData.map(c => new Coord3d(c.x, c.y, 0)))
    //clusterThingScatter.add(clusterThingData.toList.asJava)
    clusterThingScatter.setWidth(5)
    clusterThingScatter.setColor(Color.BLACK)
    val clusterChart = factory.newChart()
    clusterChart.add(clusterThingScatter)
    //clusterChart.view2d()
    clusterChart
  }
}
 */
