package eusocialcooperation.scheduler

import org.apache.pekko.actor.typed.{ActorRef, Behavior}
import org.apache.pekko.actor.typed.receptionist.Receptionist
import org.apache.pekko.actor.typed.scaladsl.Behaviors
import org.apache.pekko.actor.typed.scaladsl.ActorContext
import scala.concurrent.duration.DurationLong
import java.util.concurrent.atomic.AtomicReference
import com.typesafe.config.Config
import org.apache.pekko.actor.typed.PostStop
import javax.xml.crypto.Data
import org.apache.pekko.actor.typed.scaladsl.AskPattern.Askable
import org.apache.pekko.actor.typed.Scheduler
import org.apache.pekko.util.Timeout
import scala.concurrent.Future
import scala.concurrent.Await

/** This actor represents the "world" that the agents can see. It starts the
  * various workers and references, but it is only accessed by the workers so
  * that they can "see" which other workers are advertising prospects they have
  * found. In other applications, this can be replaced by agents returning to a
  * rendevous point and interacting with each other through Bluetooth BLE,
  * flashing lights, etc. That it does not assign workers to specific tasks or
  * perform any priority filtering of the data except to expire messages based
  * on the reported desired expiration time is important to understanding the
  * difference between this and, for example, the Bees Algorithm of Pham,
  * Ghanbarzadeh, et al. (https://en.wikipedia.org/wiki/Bees_algorithm) That
  * difference is what makes this algorithm generalizable to other eusocial
  * behaviors, like bee bearding, and human emergent behaviors such as supply
  * and demand.
  */
object Dispatcher {

  val dispatcherConfigKey = "dispatcher"
  val numWorkersConfigKey = "numWorkers"

  /** The trait that represents incoming messages to the dispatcher.
    */
  sealed trait Command

  /** A request to add a prospect discovered by an explorer.
    * @param point
    *   The prospect to be added.
    * @param delayMs
    *   The time in milliseconds after which the prospect should be removed from
    *   the list of prospects.
    */
  final case class AddProspect(point: DataPoint[Point], delayMs: Long)
      extends Command

  /** A request to see the tasks being advertised by explorers.
    * @param replyTo
    *   The actor reference to which to send the list of prospects.
    */
  final case class RequestPoints(replyTo: ActorRef[RequestedPoints])
      extends Command

  /** A request to remove a prospect from the list of advertised prospects. This
    * message should only be sent by the scheduler in response to a scheduled
    * event.
    * @param point
    *   The prospect to be removed.
    */
  final case class RemoveProspect(point: DataPoint[Point]) extends Command

  /** A request to stop the dispatcher and all workers. This is used to
    * gracefully stop the services; otherwise, stopping the actors in response
    * to PostStop resulted in workers not being able to finish their
    * transactions with the DataPointActors and nothing stopping gracefully.
    * Maybe I've fixed it, but I'm not going back.
    *
    * @param replyTo
    *   The actor reference to which to send the stop confirmation.
    */
  final case class Stop(replyTo: ActorRef[Response]) extends Command

  /** A message sent to the dispatcher when all workers have been stopped to
    * avoid locking the actor threads while other actors need to finish
    * interactions with the DataPointActors or receving messages to stop
    * themselves.
    *
    * @param replyTo
    *   The actor reference to which to send the stop confirmation.
    */
  final case class WorkersStopped(replyTo: ActorRef[Response]) extends Command

  /** The trait that represents outgoing messages from the dispatcher.
    */
  sealed trait Response

  /** The prospects being advertised by the explorers.
    *
    * @param points
    *   The set of prospects being advertised by the explorers.
    */
  final case class RequestedPoints(points: Set[DataPoint[Point]])
      extends Response

  /** Confirmation that the dispatcher has successfully stopped.
    */
  final case class Stopped() extends Response

  /** The initial factory for the dispatcher actor. This is the only method that
    * should be used to create a dispatcher actor.
    *
    * @param pointsMemory
    *   A reference to the collection of points generated by the system. It is
    *   expected that this is provided empty, and the client retains a reference
    *   to this container to inspect the points after the algorithm completes.
    * @param prospectsMemory
    *   A reference to the collection of prospects generated by the system. It
    *   is expected that this is provided empty, and the client retains a
    *   reference to this container to inspect the prospects after the algorithm
    *   completes.
    * @param appConfig
    *   The configuration object the dispatcher will use to access global
    *   configuration parameters. It is expected that the configuration contains
    *   the key {@see}
    * @param mdc
    *   The MDC configuration to use for the dispatcher and all of its child
    *   actors. This is used to direct logging output to the experiment-specific
    *   workspace to provide better traceability of the algorithm.
    * @return
    */
  def apply(
      pointsMemory: AtomicReference[Set[DataPoint[Sample]]],
      prospectsMemory: AtomicReference[Set[DataPoint[Point]]]
  )(implicit appConfig: Config, mdc: Map[String, String]): Behavior[Command] =
    Behaviors.withMdc(mdc)(
      Behaviors.setup { ctx =>
        val localConfig = appConfig.getConfig(dispatcherConfigKey)
        val numWorkers = {
          val num = localConfig.getInt(numWorkersConfigKey)
          if (num < 1) {
            throw new IllegalArgumentException(
              s"numWorkers must be at least 1, but got $num"
            )
          }
          num
        }
        val sampleActor =
          ctx.spawn(DataPointActor[Sample](pointsMemory), "sampleActor")
        val pointActor = ctx.spawn(
          DataPointActor[Point](prospectsMemory),
          "pointActor"
        )

        var workers = Set.empty[ActorRef[Worker.Command]]
        ctx.log.trace("Spawning {} workers.", numWorkers)
        (1 to numWorkers).foreach { i =>
          workers += ctx.spawn(Worker(kernel, ctx.self), s"worker-$i")
        }
        active(
          Set.empty,
          sampleActor,
          pointActor,
          workers,
          ctx
        )
      }
    )

  /** Generates the main behavior of the dispatcher, after the DataPointActors
    * and the workers have been started.
    *
    * @param prospects
    *   The list of prospects reported by explorers to the dispatcher.
    * @param sampleActor
    *   The actor used to create DataPoint[Sample] objects.
    * @param pointActor
    *   The actor used to create DataPoint[Point] objects.
    * @param workers
    *   The workers created.
    * @param ctx
    *   The context used to create the actor that provides access to logging and
    *   other utilities.
    * @return
    *   The behavior of the actor to use in subsequent calls.
    */
  private def active(
      prospects: Set[DataPoint[Point]],
      sampleActor: ActorRef[DataPointActor.Command],
      pointActor: ActorRef[DataPointActor.Command],
      workers: Set[ActorRef[Worker.Command]],
      ctx: ActorContext[Command]
  ): Behavior[Command] =
    Behaviors.receiveMessage[Command] {
      // case AddPoint(point) =>
      //  active(points + point, prospects, ctx)
      case AddProspect(point, delayMs) =>
        ctx.log.info(s"Adding prospect: $point with delay: $delayMs ms")
        ctx.scheduleOnce(delayMs.milliseconds, ctx.self, RemoveProspect(point))
        active(
          prospects + point,
          sampleActor,
          pointActor,
          workers,
          ctx
        )
      case RemoveProspect(point) =>
        ctx.log.info(s"Removing prospect: $point")
        active(
          prospects - point,
          sampleActor,
          pointActor,
          workers,
          ctx
        )
      case RequestPoints(replyTo) =>
        replyTo ! RequestedPoints(prospects)
        active(
          prospects,
          sampleActor,
          pointActor,
          workers,
          ctx
        )
      case Stop(replyTo: ActorRef[Response]) =>
        ctx.log.info("Received stop command, terminating workers and self.")
        given Scheduler = ctx.system.scheduler
        given Timeout = 5.seconds
        given scala.concurrent.ExecutionContext =
          scala.concurrent.ExecutionContext.global
        ctx.pipeToSelf(Future.sequence(workers.map(_.ask(Worker.Stop(_))))) {
          case scala.util.Success(_) =>
            ctx.log.info("All workers stopped successfully.")
            WorkersStopped(replyTo)
          case scala.util.Failure(e) =>
            ctx.log.error("Error while stopping workers: {}", e.getMessage)
            WorkersStopped(
              replyTo
            ) // Still attempt to stop self even if workers fail to stop
        }
        Behaviors.same
      case WorkersStopped(replyTo) =>
        ctx.log.info("All workers have been stopped, now stopping dispatcher.")
        ctx.stop(sampleActor)
        ctx.stop(pointActor)
        replyTo ! Stopped()
        Behaviors.stopped
    }
}
