package eusocialcooperation.scheduler.datapoint

import org.apache.pekko.actor.typed.ActorRef
import org.apache.pekko.actor.typed.Scheduler
import org.apache.pekko.util.Timeout

import scala.concurrent.duration.DurationInt
import scala.concurrent.Await
import org.apache.pekko.actor.typed.scaladsl.AskPattern.Askable
import scala.concurrent.duration.Duration

object PekkoDataPoint {
  /** Generates a 'unit' operation to 'lift' a value of type A to a
   * DataPoint[A]. With this unit operator, the DataPoint is generated by a
   * Pekko actor that stores the value..
    *
    * @param dpa
    *   The actor used to create the DataPoint.
    * @param scheduler
    *   The Apache Pekko scheduler used to coordinate messages, since this
    *   constructor requires a return message.
    * @return
    *   The DataPoint containing the value, with the metadata provided by the
    *   implicit parameters and the actor message.
    */
  def getActorDataPointUnit[A](dpa: ActorRef[DataPointActor.Create[A]], scheduler: Scheduler): DataPoint.DataPointUnit[A] = {
    (value) => (context, parent) ?=> {
      implicit val timeout: Timeout = Timeout(3.seconds)
      //val worker: String = Thread.currentThread().getName

      // Using Inf because the pekko ask function takes a timeout, and it's specified above.
      Await.result(
        dpa.ask[DataPoint[A]](replyTo =>
          DataPointActor.Create(value, context, replyTo, parent)
        )(using scheduler = scheduler),
        Duration.Inf
      )
    }
  }

}
