eusocialcooperation.scheduler {
    duration = 10 s
    dispatcher {
        numWorkers = 10
    }
    workers {
        loopDelay = 50 ms
        weightPerProspect = 0.3
        explorer {
            numPointsToExplore = 10
            threshold = 0.05
            explorationRadius = 0.01
            delayPerProspect = 3 ms
        }
        exploiter {
            increment = 0.001
            fuzziness = 0.01
        }
    }
}
